services:
  # 1. Base de Datos PostgreSQL
  postgres_db:
    image: postgres:15
    container_name: nethome_postgres
    restart: always
    environment:
      POSTGRES_USER: nethome_user
      POSTGRES_PASSWORD: nethome_password
      POSTGRES_DB: nethome_iot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Broker MQTT (Mosquitto)
  mqtt_broker:
    image: eclipse-mosquitto:2
    container_name: nethome_mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 3. Capa de API (FastAPI)
  backend_api:
    build: .
    container_name: nethome_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres_db
      - mqtt_broker
    env_file:
      - .env

  # 4. Capa de IoT (Worker MQTT)
  mqtt_worker:
    build: .
    container_name: nethome_mqtt_worker
    restart: always
    command: python -u -m mqtt.oyente_mqtt
    depends_on:
      - postgres_db
      - mqtt_broker
    env_file:
      - .env

volumes:
  postgres_data: